# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 404)
        self.labelwelcome = QtWidgets.QLabel(MainWindow)
        self.labelwelcome.setGeometry(QtCore.QRect(90, 10, 201, 141))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.labelwelcome.setFont(font)
        self.labelwelcome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelwelcome.setTextFormat(QtCore.Qt.AutoText)
        self.labelwelcome.setScaledContents(False)
        self.labelwelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labelwelcome.setWordWrap(False)
        self.labelwelcome.setOpenExternalLinks(False)
        self.labelwelcome.setObjectName("labelwelcome")
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(110, 320, 181, 51))
        self.label.setObjectName("label")
        self.Buttonoccam = QtWidgets.QPushButton(MainWindow)
        self.Buttonoccam.setGeometry(QtCore.QRect(80, 160, 231, 31))
        self.Buttonoccam.setObjectName("Buttonoccam")
        self.Buttonreadme = QtWidgets.QPushButton(MainWindow)
        self.Buttonreadme.setGeometry(QtCore.QRect(80, 210, 231, 31))
        self.Buttonreadme.setObjectName("Buttonreadme")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelwelcome.setText(_translate("MainWindow", "MT Inversion"))
        self.label.setText(_translate("MainWindow", "Copyright@MaoFangyuan"))
        self.Buttonoccam.setText(_translate("MainWindow", "Occam1D Inversion"))
        self.Buttonreadme.setText(_translate("MainWindow", "Introduction"))
